# Generated by Django 4.0.3 on 2022-04-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='createBy',
            new_name='createdBy',
        ),
    ]
