# Generated by Django 4.0.3 on 2022-04-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_notes_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
