# Generated by Django 4.0.3 on 2022-04-01 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_notes_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='createdAt',
            new_name='created_At',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='createdBy',
            new_name='created_By',
        ),
    ]
