# Generated by Django 4.0.3 on 2022-04-01 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_rename_createdat_note_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_By',
        ),
        migrations.AddField(
            model_name='note',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='note', to=settings.AUTH_USER_MODEL),
        ),
    ]
