# Generated by Django 4.0.3 on 2022-04-30 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_remove_note_created_by_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='email',
            field=models.EmailField(default='Admin', max_length=225),
        ),
        migrations.AlterField(
            model_name='note',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to=settings.AUTH_USER_MODEL),
        ),
    ]
