# Generated by Django 4.0.3 on 2022-05-05 16:18

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_note_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='recommendations',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
