# Generated by Django 4.0.3 on 2022-05-05 16:25

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_note_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='recommendations',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
    ]
