# Generated by Django 4.0.3 on 2022-05-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_note_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='recommendations',
            field=models.JSONField(null=True),
        ),
    ]
